
name: Deploy Database

on:
  workflow_call:
    inputs:
      domain:
        description: 'Domain to deploy the database'
        required: true
        type: string


permissions:
  contents: read

jobs:
  seserser:
    name: Build Backend app
    runs-on: ubuntu-latest

    steps:
    - name: build pims-api
      run: echo "Builing app"
    - name: store image
      run: echo "storing app image"

  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    environment: ${{inputs.domain}}

    steps:
    - name: Copy frontend
      run: echo "coping frontend to ${{inputs.domain}}"
    - name: Deploy frontend
      run: echo "deploying frontend to ${{inputs.domain}}"

  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    environment: ${{inputs.domain}}

    steps:
    - name: Copy backend
      run: echo "coping backend to ${{inputs.domain}}"
    - name: Deploy backend
      run: echo "deploying backend to ${{inputs.domain}}"

  deploy-database:
    name: Deploy database
    runs-on: ubuntu-latest
    environment: ${{inputs.domain}}

    steps:
    - name: Copy database
      run: echo "coping database to ${{inputs.domain}}"
    - name: Deploy database
      run: echo "deploying database to ${{inputs.domain}}"
