
name: Demo - Application deployment

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'lalala'
        default: 'fii'
        required: true

env:
  MY_PROD_SECRET: ${{ secrets.LE_SECRET }}                   # set this to your preferred AWS region, e.g. us-west-1


permissions:
  contents: read

jobs:
  build-api:
    name: Build Backend app
    runs-on: ubuntu-latest

    steps:
    - name: build pims-api
      run: echo "Building app"
    - name: store image
      run: echo "storing app image"

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Build Frontend app
      run: echo "bBuilding frontendapp"
    - name: TEST Secrety
      run: echo "storing frontend image"

  deploy-dev:
    environment: dev
    uses: ./.github/workflows/demo-db-deploy.yml
    with:
      domain: dev
    needs: [build-api, build-frontend]

  deploy-test:
    uses: ./.github/workflows/demo-db-deploy.yml
    environment: test
    with:
      domain: test
    needs: [deploy-dev]

  deploy-uat:
    uses: ./.github/workflows/demo-db-deploy.yml
    environment: uat
    with:
      domain: uat
    needs: [deploy-test]

  deploy-prod:
    uses: ./.github/workflows/demo-db-deploy.yml
    environment: prod
    with:
      domain: prod
    needs: [deploy-uat]
